
version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - npm install
      - npm run clientinstall
  # build:
  #   commands:
  #     - npm start
artifacts:
  files:
    - '**/*'